### ISSUE TITLE
Reloader for Main process

### ISSUE THREAD

**Issue by philcockfield** [shamofu/electron-react-parcel-boilerplate#3]
@shamofu - thanks SO MUCH for putting this boilerplate together!  Hugely helpful 🍰💪.

----

I notice the `main` process does not auto re-load on changes (is that right, or am I missing something?).  Makes sense as that's outside the purview of parcel, I guess.  

But projects like `electron-webpack` seem to have figured out how to do HMR on `main`.  Is this intentionally left out?  Or do you have a strategy for how this might be done?  Or (as above) and I missing something 😛.

Thanks.

**Comment by shamofu** [comment]
Glad to hear that!

---

HMR on `main` process is intentionally left out for now because somehow `Parcel 2` will support it in the future. (https://github.com/parcel-bundler/parcel/issues/2492)
However, I will try to implement it in other ways until then.

If you have any other questions, feel free to ask me!

**Comment by philcockfield** [comment]
Oh, interesting! `parcel-2`...reading up on that now.  Thanks.

**Comment by polarathene** [comment]
Might be worth mentioning the HMR support in the readme isn't available presently? 

There is a [tracking issue here](https://github.com/parcel-bundler/parcel/issues/1841) which appears to have some workarounds mentioned if you want to go that route? Parcel 2 still l[ooks like it's a while away](https://github.com/parcel-bundler/parcel/issues/2567) (17.7% complete so far) ([Project Board](https://github.com/parcel-bundler/parcel/projects/5))
